# Generated by Django 5.1.4 on 2025-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds for voice notes', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice Note')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='voice_notes/'),
        ),
    ]
